name: Update Time Zone Database
on:
  workflow_dispatch:
jobs:
  update:
    name: Update Iana tzdb
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Create temporary directory for files
      run: mkdir tzdata
    - name: Download Iana TZ DB
      run: wget https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz -P tzdata
    - name: Unpack TAR file
      run: gzip -dc tzdata/tzdata-latest.tar.gz | tar -xf - -C tzdata
    - name: Build TZ file
      run: node src/buildTz.js
    - name: Build package
      run: npm run build
    - name: Remove temporary directory
      run: rm tzdata -R
    - name: Commit build
      uses: stefanzweifel/git-auto-commit-action@v4.15.1
      with:
        commit_message: ":package: Update Iana Time Zone Data  [skip ci]"
        commit_user_name: BetaHuhn Bot
        commit_user_email: bot@mxis.ch
        commit_author: BetaHuhn Bot <bot@mxis.ch>
